import { NERVE_NAMES, NerveId, NerveType, type ReferenceValue } from './types.ts';

// Canonical nerve metadata only; empirical scoring limits have one source of truth in analysis.ts.
export const DEFAULT_REFERENCES: ReferenceValue[] = [
  {
    nerveId: NerveId.TIBIAL,
    nerveName: NERVE_NAMES[NerveId.TIBIAL],
    type: NerveType.MOTOR
  },
  {
    nerveId: NerveId.FIBULAR,
    nerveName: NERVE_NAMES[NerveId.FIBULAR],
    type: NerveType.MOTOR
  },
  {
    nerveId: NerveId.ULNAR,
    nerveName: NERVE_NAMES[NerveId.ULNAR],
    type: NerveType.MOTOR
  },
  {
    nerveId: NerveId.SURAL,
    nerveName: NERVE_NAMES[NerveId.SURAL],
    type: NerveType.SENSORY
  }
];

export const TEXTS = {
  es: {
    title: "Polineuropathy-Assistant PMR",
    subtitle: "Score electrodiagnóstico percentilar adaptado para apoyo al diagnóstico y cuantificación de la polineuropatía diabética.",
    professionalTool: "HERRAMIENTA PROFESIONAL",
    basedOn: "Score electrodiagnóstico percentilar adaptado del enfoque de puntuación compuesta descrito por Davies et al.",
    patientInfo: "Información del Paciente",
    age: "Edad",
    height: "Altura (cm)",
    weight: "Peso (kg)",
    symptoms: "Signos de Polineuropatía",
    symptomsOptions: {
      NONE: 'Sin signos de neuropatía',
      FEET_LEGS: 'Signos de polineuropatía en pies o piernas',
      THIGH: 'Signos de afectación en muslo'
    },
    calculateBtn: "CALCULAR SCORES #2 Y #4",
    processing: "PROCESANDO...",
    readingsTitle: "Lecturas de Neuroconducción",
    nerveHeader: "Nervio",
    paramHeader: "Parámetro 1",
    ampHeader: "Amplitud",
    ampHeaderSural: "Amp. Inicio a Pico",
    velocity: "VELOCIDAD (m/s)",
    latency: "LAT. PICO (ms)",
    ampUnitSural: "uV",
    ampUnitMotor: "mV",
    finalClass: "Clasificación Electrofisiológica",
    diagnosis: "Diagnóstico",
    severity: "SEVERIDAD",
    score2Title: "Score #2 — Criterio diagnóstico compuesto",
    score4Title: "Score #4 — Severidad por amplitudes",
    copySummary: "COPIAR RESUMEN PARA INFORME",
    copied: "Copiado",
    ageValidation: "La edad debe estar entre 19 y 79 años para calcular los scores.",
    heightValidation: "La talla debe ser un número válido mayor que 0 cm.",
    incompleteAnalysis: "No es posible calcular los scores: existen parámetros faltantes o inválidos.",
    printReport: "Imprimir Informe",
    aiAssistant: "Asistente Inteligente PM&R",
    aiPrompt: "Genere un resumen clínico basado en los hallazgos electrofisiológicos usando IA.",
    aiBtn: "Generar Concepto Clínico",
    aiRegen: "Regenerar o Limpiar",
    references: "Referencias",
    development: "Desarrollo",
    footerPurpose: "Clinimetría diseñada para uso por profesionales en Medicina Electrodiagnóstica y Neuromuscular (Medicina Física y Rehabilitación o Neurología).",
    footerDeveloper: "Desarrollado por Dr. Pastor Leonardo Jurado Escobar",
    footerSpecialty: "Especialista en Medicina Física y Rehabilitación · UNAL",
    footerCopyright: "© 2026 · Todos los derechos reservados.",
    normal: "NORMAL",
    abnormal: "ANORMAL",
    mild: "LEVE",
    moderate: "MODERADA",
    severe: "SEVERA",
    noAxonalDamage: "SIN EVIDENCIA DE DAÑO AXONAL",
    points: "PTS",
    // Interpretation strings updated to specific phrases
    s2NormalTitle: "NORMAL",
    s2NormalBody: "Los parámetros de conducción evaluados se encuentran dentro de los límites empíricos de referencia. No cumple criterio electrodiagnóstico compuesto para polineuropatía diabética.",
    s2SensorimotorBody: "Neuroconducciones anormales que cumplen el criterio electrodiagnóstico compuesto, con patrón sensitivo-motor compatible con polineuropatía en el contexto clínico apropiado.",
    s2AbnormalGeneric: "Neuroconducciones anormales que cumplen el criterio electrodiagnóstico compuesto por alteración de ≥2 nervios motores. Hallazgo compatible con polineuropatía en el contexto clínico apropiado; correlacionar con los hallazgos sensitivos y clínicos.",
    nStageLabel: "Estadiaje N",
    n0Desc: "N0: No cumple criterio electrodiagnóstico compuesto de Score #2. Puede existir una alteración aislada en un nervio.",
    n1Desc: "Neuroconducciones anormales sin signos de neuropatía",
    n2Desc: "Neuroconducciones anormales y signos de polineuropatía en pies o piernas",
    n3Desc: "Neuroconducciones anormales y signos de afectación del muslo"
  },
  en: {
    title: "Polineuropathy-Assistant PMR",
    subtitle: "Adapted percentile-based electrodiagnostic score for diagnostic support and quantification of diabetic polyneuropathy.",
    professionalTool: "PROFESSIONAL TOOL",
    basedOn: "Percentile-based electrodiagnostic score adapted from the compound scoring approach described by Davies et al.",
    patientInfo: "Patient Information",
    age: "Age",
    height: "Height (cm)",
    weight: "Weight (kg)",
    symptoms: "Polyneuropathy Signs",
    symptomsOptions: {
      NONE: 'No signs of neuropathy',
      FEET_LEGS: 'Signs of polyneuropathy in feet or legs',
      THIGH: 'Signs of involvement in thigh'
    },
    calculateBtn: "CALCULATE SCORES #2 & #4",
    processing: "PROCESSING...",
    readingsTitle: "Nerve Conduction Readings",
    nerveHeader: "Nerve",
    paramHeader: "Parameter 1",
    ampHeader: "Amplitude",
    ampHeaderSural: "Onset to Peak Amp.",
    velocity: "VELOCITY (m/s)",
    latency: "PEAK LAT. (ms)",
    ampUnitSural: "uV",
    ampUnitMotor: "mV",
    finalClass: "Electrophysiological Classification",
    diagnosis: "Diagnosis",
    severity: "SEVERITY",
    score2Title: "Score #2 — Composite diagnostic criterion",
    score4Title: "Score #4 — Amplitude severity",
    copySummary: "COPY SUMMARY FOR REPORT",
    copied: "Copied",
    ageValidation: "Age must be between 19 and 79 years to calculate the scores.",
    heightValidation: "Height must be a valid number greater than 0 cm.",
    incompleteAnalysis: "Scores cannot be calculated because required parameters are missing or invalid.",
    printReport: "Print Report",
    aiAssistant: "PM&R Smart Assistant",
    aiPrompt: "Generate a clinical summary based on electrophysiological findings using AI.",
    aiBtn: "Generate Clinical Concept",
    aiRegen: "Regenerate or Clear",
    references: "References",
    development: "Development",
    footerPurpose: "Clinimetrics designed for use by professionals in Electrodiagnostic and Neuromuscular Medicine (Physical Medicine and Rehabilitation or Neurology).",
    footerDeveloper: "Developed by Dr. Pastor Leonardo Jurado Escobar",
    footerSpecialty: "Specialist in Physical Medicine and Rehabilitation · UNAL",
    footerCopyright: "© 2026 · All rights reserved.",
    normal: "NORMAL",
    abnormal: "ABNORMAL",
    mild: "MILD",
    moderate: "MODERATE",
    severe: "SEVERE",
    noAxonalDamage: "NO EVIDENCE OF AXONAL DAMAGE",
    points: "PTS",
    // Interpretation strings
    s2NormalTitle: "NORMAL",
    s2NormalBody: "The evaluated conduction parameters are within empirical reference limits. The composite electrodiagnostic criterion for diabetic polyneuropathy is not met.",
    s2SensorimotorBody: "Abnormal nerve conductions meet the composite electrodiagnostic criterion, with a sensorimotor pattern compatible with polyneuropathy in the appropriate clinical context.",
    s2AbnormalGeneric: "Abnormal nerve conductions meet the composite electrodiagnostic criterion through abnormality in ≥2 motor nerves. This finding is compatible with polyneuropathy in the appropriate clinical context; correlate with sensory and clinical findings.",
    nStageLabel: "N Staging",
    n0Desc: "N0: Does not meet the Score #2 composite electrodiagnostic criterion. An isolated abnormality in one nerve may be present.",
    n1Desc: "Abnormal nerve conductions without signs of neuropathy",
    n2Desc: "Abnormal nerve conductions and signs of polyneuropathy in feet or legs",
    n3Desc: "Abnormal nerve conductions and signs of thigh involvement"
  }
};
