import test from 'node:test';import assert from 'node:assert/strict';
import { calculateEmpiricalPoints,classifyScore2,getEmpiricalRule,getFibularAmpStats,getScore4Severity,getTibialAmpStats,runFullAnalysis } from '../utils/analysis.ts';
import { buildClinicalReportText,formatPercentile } from '../utils/report.ts';import { NerveId,NerveType,type NerveReading } from '../types.ts';import { displayMeasurementInput,updatePairedMeasurement } from '../utils/input.ts';import { DEFAULT_REFERENCES,TEXTS } from '../constants.ts';
const valid=():NerveReading[]=>[{nerveId:NerveId.TIBIAL,nerveName:'Tibial (Motor)',type:NerveType.MOTOR,distalLatency:'',amplitude:15.3,velocity:51},{nerveId:NerveId.FIBULAR,nerveName:'Fibular (Motor)',type:NerveType.MOTOR,distalLatency:'',amplitude:6.8,velocity:49},{nerveId:NerveId.ULNAR,nerveName:'Ulnar (Motor)',type:NerveType.MOTOR,distalLatency:'',amplitude:11.6,velocity:61},{nerveId:NerveId.SURAL,nerveName:'Sural (Sensitivo)',type:NerveType.SENSORY,distalLatency:'',peakLatency:3.8,amplitude:17,velocity:''}];
const analyze=(r=valid(),age=20,height=155)=>runFullAnalysis(r,{age,height});const absent=(id:NerveId,r=valid())=>set(id,'amplitude','NR',set(id,id===NerveId.SURAL?'peakLatency':'velocity','NR',r));const set=(id:NerveId,key:'velocity'|'peakLatency'|'amplitude',value:number|string,r=valid())=>r.map(x=>x.nerveId===id?{...x,[key]:value}:x);
test('all empirical strata have inclusive normal boundary and just-below abnormal lower limits',()=>{const cases:[NerveId,'velocity'|'amplitude',number,number,number][]=[
 [NerveId.TIBIAL,'velocity',19,159,44],[NerveId.TIBIAL,'velocity',49,160,42],[NerveId.TIBIAL,'velocity',49,170,37],[NerveId.TIBIAL,'velocity',50,159,40],[NerveId.TIBIAL,'velocity',79,160,37],[NerveId.TIBIAL,'velocity',79,170,34],
 [NerveId.FIBULAR,'velocity',19,169,43],[NerveId.FIBULAR,'velocity',39,170,37],[NerveId.FIBULAR,'velocity',40,169,39],[NerveId.FIBULAR,'velocity',79,170,36],
 [NerveId.TIBIAL,'amplitude',19,170,5.8],[NerveId.TIBIAL,'amplitude',30,170,5.3],[NerveId.TIBIAL,'amplitude',60,170,1.1],[NerveId.FIBULAR,'amplitude',19,170,2.6],[NerveId.FIBULAR,'amplitude',40,170,1.1],[NerveId.ULNAR,'velocity',20,170,52],[NerveId.ULNAR,'amplitude',20,170,7.9],[NerveId.SURAL,'amplitude',20,170,4]];
 for(const [id,param,age,height,cutoff] of cases){const rule=getEmpiricalRule(id,param,age,height);assert.equal(rule.empiricalCutoff,cutoff);assert.equal(calculateEmpiricalPoints(cutoff,rule),0);assert.equal(calculateEmpiricalPoints(cutoff-.001,rule),1);}});
test('sural latency boundary, above, and NR',()=>{assert.equal(analyze(set(NerveId.SURAL,'peakLatency',4.5)).score2.details[3].points,0);assert.equal(analyze(set(NerveId.SURAL,'peakLatency',4.5001)).score2.details[3].points,1);assert.equal(analyze(absent(NerveId.SURAL)).score2.details[3].points,2);});
test('NR and amplitude zero score 2/display NR (0); velocity and latency zero invalidate',()=>{for(const raw of ['NR','N'])assert.ok(analyze(valid().map(r=>({...r,amplitude:raw}))).score4.details.every(d=>d.points===2));const zero=analyze(set(NerveId.TIBIAL,'velocity','NR',set(NerveId.TIBIAL,'amplitude',0)));assert.equal(zero.score4.details[0].value,'NR (0)');assert.equal(zero.score4.details[0].points,2);for(const [id,key] of [[NerveId.TIBIAL,'velocity'],[NerveId.SURAL,'peakLatency']] as const)assert.equal(analyze(set(id,key,0)).analysisStatus,'INCOMPLETE_ANALYSIS');});
test('composite criterion counts different Score #2 nerves, not points or amplitudes',()=>{let x=analyze(absent(NerveId.TIBIAL));assert.equal(x.score2.total,2);assert.equal(x.score2.abnormalNerveCount,1);assert.equal(x.score2.meetsCompositeCriterion,false);x=analyze(absent(NerveId.SURAL));assert.equal(x.score2.total,2);assert.equal(x.score2.abnormalNerveCount,1);assert.equal(x.score2.meetsCompositeCriterion,false);assert.doesNotMatch(x.score2.interpretationBody!,/sensitiva$/i);x=analyze(set(NerveId.FIBULAR,'velocity',42.9,set(NerveId.TIBIAL,'velocity',43.9)));assert.equal(x.score2.total,2);assert.equal(x.score2.abnormalNerveCount,2);assert.equal(x.score2.meetsCompositeCriterion,true);x=analyze(set(NerveId.FIBULAR,'velocity',42.9,absent(NerveId.TIBIAL)));assert.equal(x.score2.total,3);assert.equal(x.score2.meetsCompositeCriterion,true);});
test('deterministic interpretations cover normal, isolated, sensorimotor and motor composite',()=>{let x=analyze();assert.equal(x.score2.abnormalNerveCount,0);assert.match(x.score2.interpretationBody!,/límites empíricos/);x=analyze(set(NerveId.TIBIAL,'velocity',43.9));assert.match(x.score2.interpretationBody!,/aislada/);assert.doesNotMatch(x.score2.interpretationBody!,/se considera normal|neuroconducciones normales/i);x=analyze(set(NerveId.SURAL,'peakLatency',4.6,set(NerveId.TIBIAL,'velocity',43.9)));assert.match(x.score2.interpretationBody!,/sensitivo-motor/);x=analyze(set(NerveId.FIBULAR,'velocity',42.9,set(NerveId.TIBIAL,'velocity',43.9)));assert.match(x.score2.interpretationBody!,/≥2 nervios motores/);assert.doesNotMatch(x.score2.interpretationBody!,/desmiel/);});
test('Score #4 provisional severity bands remain exact',()=>assert.deepEqual([0,1,2,3,5,6,8].map(n=>getScore4Severity(n)),['SIN EVIDENCIA DE DAÑO AXONAL','LEVE','LEVE','MODERADA','MODERADA','SEVERA','SEVERA']));
test('CDF remains independently calculated and cannot determine scoring',()=>{const x=analyze(set(NerveId.ULNAR,'velocity',52));const d=x.score2.details[2];assert.ok(d.descriptiveCDFPercentile!==undefined);assert.equal(d.points,0);assert.notEqual(Number((d.descriptiveCDFPercentile!*100).toFixed(1)),3);assert.equal(formatPercentile({...d,descriptiveCDFPercentile:.0008}),'P0.08');assert.deepEqual([59,60,79].map(a=>Number(getTibialAmpStats(a).mean.toFixed(2))),[11.66,11.35,9.8]);assert.deepEqual([39,40,79].map(a=>Number(getFibularAmpStats(a).mean.toFixed(2))),[6.12,5.95,5.1]);});
test('report contains all parameters, composite data, severity, method, empirical refs and descriptive CDF only',()=>{const x=analyze(),report=buildClinicalReportText({age:20,height:155},valid(),x);assert.equal((report.match(/Ref\. empírica/g)||[]).length,8);assert.equal((report.match(/CDF descriptivo/g)||[]).length,8);for(const word of ['Score #2 total:','Nervios anormales: 0/4','Criterio compuesto:','Score #4 total:','Severidad electrofisiológica según clasificación provisional:','Método de puntuación:','Buschbacher/AANEM'])assert.match(report,new RegExp(word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(report,/CDF empírico|percentil empírico/i);assert.doesNotMatch(report,/P1\.8|P5\.5|P6\.7|P9\.7/);const nr=buildClinicalReportText({age:20,height:155},valid(),analyze(set(NerveId.TIBIAL,'velocity','NR',set(NerveId.TIBIAL,'amplitude',0))));assert.match(nr,/NR \(0\)/);assert.doesNotMatch(nr,/NR \(0\).*CDF descriptivo/);});
test('missing/invalid safeguards and canonical nerve/name validation remain',()=>{assert.equal(analyze(set(NerveId.ULNAR,'amplitude','')).analysisStatus,'INCOMPLETE_ANALYSIS');assert.equal(analyze(set(NerveId.ULNAR,'amplitude','abc')).analysisStatus,'INCOMPLETE_ANALYSIS');const mismatch=valid();mismatch[0]={...mismatch[0],nerveName:'Sural (Sensitivo)'};assert.throws(()=>analyze(mismatch),/does not match identifier/);assert.throws(()=>analyze(valid().filter(r=>r.nerveId!==NerveId.ULNAR)),/missing: ULNAR/);});
test('eligibility and numeric zero display remain',()=>{for(const age of [18,80])assert.throws(()=>analyze(valid(),age),RangeError);assert.equal(displayMeasurementInput(0),0);assert.equal(displayMeasurementInput('0'),'0');});


test('Score #2 three-state status and diagnosis classes never label isolated abnormality normal',()=>{const normal=analyze();assert.equal(normal.score2.status,'NO_ABNORMALITY');assert.equal(normal.diagnosisClass,'NORMAL');const isolated=analyze(set(NerveId.TIBIAL,'velocity',43.9));assert.equal(isolated.score2.status,'ISOLATED_ABNORMALITY');assert.equal(isolated.diagnosisClass,'ALTERACIÓN AISLADA');assert.doesNotMatch(isolated.severityClass!,/NORMAL/);const isolatedEn=runFullAnalysis(set(NerveId.TIBIAL,'velocity',43.9),{age:20,height:155},'en');assert.equal(isolatedEn.diagnosisClass,'ISOLATED ABNORMALITY');const positive=analyze(set(NerveId.FIBULAR,'velocity',42.9,set(NerveId.TIBIAL,'velocity',43.9)));assert.equal(positive.score2.status,'COMPOSITE_POSITIVE');assert.equal(positive.diagnosisClass,'ANORMAL');});
test('all NR/positive cross-field contradictions are incomplete with inconsistency issue',()=>{for(const id of Object.values(NerveId)){const main=id===NerveId.SURAL?'peakLatency':'velocity';for(const r of [set(id,'amplitude','NR'),set(id,main,'NR')]){const x=analyze(r);assert.equal(x.analysisStatus,'INCOMPLETE_ANALYSIS');assert.ok(x.issues.some(i=>i.nerveId===id&&i.status==='INCONSISTENT'));}}});
test('blank paired fields auto-fill NR without overwriting contradictory entered values',()=>{for(const id of Object.values(NerveId)){const main=id===NerveId.SURAL?'peakLatency':'velocity';const base=valid().find(r=>r.nerveId===id)!;let blank={...base,[main]:'',amplitude:''};assert.equal(updatePairedMeasurement(blank,'amplitude',0)[main],'NR');assert.equal(updatePairedMeasurement(blank,main,'NR').amplitude,'NR');assert.equal(updatePairedMeasurement({...blank,[main]:45},'amplitude','NR')[main],45);assert.equal(updatePairedMeasurement({...blank,amplitude:5},main,'NR').amplitude,5);}});
test('unsupported empirical nerve/parameter combinations throw explicitly',()=>{assert.throws(()=>getEmpiricalRule(NerveId.SURAL,'velocity',20,170),/Unsupported empirical rule combination/);assert.throws(()=>getEmpiricalRule(NerveId.TIBIAL,'peakLatency',20,170),/Unsupported empirical rule combination/);});
test('terminology, ulnar operational label, empirical reference format and metadata cleanup',()=>{assert.equal(TEXTS.en.score2Title,'Score #2 — Composite diagnostic criterion');assert.equal(TEXTS.en.score4Title,'Score #4 — Amplitude severity');const report=buildClinicalReportText({age:20,height:155},valid(),analyze(),'en');assert.match(report,/Ulnar forearm motor conduction velocity \(below elbow\)/);assert.match(report,/P3 LLN = 52 m\/s; normal ≥52 m\/s/);const es=buildClinicalReportText({age:20,height:155},valid(),analyze(),'es');assert.match(es,/P97 LSN = 4\.5 ms; normal ≤4\.5 ms/);assert.ok(DEFAULT_REFERENCES.every(r=>Object.keys(r).sort().join(',')==='nerveId,nerveName,type'));});
test('Score #4-only abnormality does not increase Score #2 abnormal nerve count',()=>{const x=analyze(set(NerveId.TIBIAL,'amplitude',5.7));assert.equal(x.score4.details[0].points,1);assert.equal(x.score2.abnormalNerveCount,0);assert.equal(x.score2.status,'NO_ABNORMALITY');});

test('report and staging documentation explicitly identify provisional severity',()=>{const es=buildClinicalReportText({age:20,height:155},valid(),analyze(),'es');assert.match(es,/Severidad electrofisiológica según clasificación provisional:/);assert.match(es,/se conserva de manera provisional y requiere validación clínica independiente/);const en=buildClinicalReportText({age:20,height:155},valid(),analyze(),'en');assert.match(en,/Electrophysiological severity according to the provisional classification:/);assert.match(en,/retained provisionally and requires independent clinical validation/);assert.match(TEXTS.es.n0Desc,/No cumple criterio electrodiagnóstico compuesto/);assert.match(TEXTS.en.n0Desc,/Does not meet the Score #2 composite electrodiagnostic criterion/);});
