import React from 'react';
import { ScientificReferences } from './ScientificReferences';

type Language = 'es' | 'en';

const score2Limits = {
  es: [
    { title: 'Velocidad motora tibial', items: ['19–49 años, talla <160 cm: normal ≥44 m/s', '19–49 años, talla 160–169.999 cm: normal ≥42 m/s', '19–49 años, talla ≥170 cm: normal ≥37 m/s', '50–79 años, talla <160 cm: normal ≥40 m/s', '50–79 años, talla 160–169.999 cm: normal ≥37 m/s', '50–79 años, talla ≥170 cm: normal ≥34 m/s'] },
    { title: 'Velocidad motora fibular/peronea', items: ['19–39 años, talla <170 cm: normal ≥43 m/s', '19–39 años, talla ≥170 cm: normal ≥37 m/s', '40–79 años, talla <170 cm: normal ≥39 m/s', '40–79 años, talla ≥170 cm: normal ≥36 m/s'] },
    { title: 'Velocidad motora ulnar', items: ['Velocidad motora ulnar de antebrazo (below elbow): normal ≥52 m/s'] },
    { title: 'Latencia pico sural', items: ['Latencia pico sural: normal ≤4.5 ms', 'Compatible con técnica sural antidrómica de 14 cm.'] }
  ],
  en: [
    { title: 'Tibial motor velocity', items: ['Age 19–49, height <160 cm: normal ≥44 m/s', 'Age 19–49, height 160–169.999 cm: normal ≥42 m/s', 'Age 19–49, height ≥170 cm: normal ≥37 m/s', 'Age 50–79, height <160 cm: normal ≥40 m/s', 'Age 50–79, height 160–169.999 cm: normal ≥37 m/s', 'Age 50–79, height ≥170 cm: normal ≥34 m/s'] },
    { title: 'Fibular/peroneal motor velocity', items: ['Age 19–39, height <170 cm: normal ≥43 m/s', 'Age 19–39, height ≥170 cm: normal ≥37 m/s', 'Age 40–79, height <170 cm: normal ≥39 m/s', 'Age 40–79, height ≥170 cm: normal ≥36 m/s'] },
    { title: 'Ulnar motor velocity', items: ['Forearm ulnar motor velocity (below elbow): normal ≥52 m/s'] },
    { title: 'Sural peak latency', items: ['Sural peak latency: normal ≤4.5 ms', 'Compatible with a 14-cm antidromic sural technique.'] }
  ]
};

const score4Limits = {
  es: [
    { title: 'CMAP tibial', items: ['19–29 años: normal ≥5.8 mV', '30–59 años: normal ≥5.3 mV', '60–79 años: normal ≥1.1 mV'] },
    { title: 'CMAP fibular/peroneo', items: ['19–39 años: normal ≥2.6 mV', '40–79 años: normal ≥1.1 mV'] },
    { title: 'CMAP ulnar', items: ['Normal ≥7.9 mV'] },
    { title: 'SNAP sural inicio a pico', items: ['Normal ≥4.0 µV', 'Compatible con técnica sural antidrómica de 14 cm.'] }
  ],
  en: [
    { title: 'Tibial CMAP', items: ['Age 19–29: normal ≥5.8 mV', 'Age 30–59: normal ≥5.3 mV', 'Age 60–79: normal ≥1.1 mV'] },
    { title: 'Fibular/peroneal CMAP', items: ['Age 19–39: normal ≥2.6 mV', 'Age 40–79: normal ≥1.1 mV'] },
    { title: 'Ulnar CMAP', items: ['Normal ≥7.9 mV'] },
    { title: 'Sural SNAP onset-to-peak', items: ['Normal ≥4.0 µV', 'Compatible with a 14-cm antidromic sural technique.'] }
  ]
};

const LimitCards = ({ groups }: { groups: Array<{ title: string; items: string[] }> }) => (
  <div className="grid grid-cols-1 md:grid-cols-2 gap-3 my-4">
    {groups.map(group => <div key={group.title} className="rounded-lg border border-slate-200 bg-white p-4 min-w-0">
      <h4 className="font-bold text-slate-800 mb-2">{group.title}</h4>
      <ul className="space-y-1.5 text-slate-600">{group.items.map(item => <li key={item} className="break-words">• {item}</li>)}</ul>
    </div>)}
  </div>
);

const Section = ({ title, children }: React.PropsWithChildren<{ title: string }>) => <section className="space-y-3">
  <h3 className="text-base md:text-lg font-bold text-slate-900 border-b border-slate-200 pb-2">{title}</h3>{children}
</section>;

export const DevelopmentContent: React.FC<{ lang: Language }> = ({ lang }) => {
  if (lang === 'es') return <article className="p-5 md:p-7 border-t border-slate-100 bg-slate-50 text-sm md:text-[15px] text-slate-700 leading-relaxed space-y-8">
    <header className="space-y-3"><h2 className="text-xl md:text-2xl font-bold text-slate-900">¿Cómo funciona este sistema de puntuación?</h2>
      <p>Esta aplicación es una herramienta de apoyo al análisis electrodiagnóstico de la polineuropatía diabética distal simétrica sensitivo-motora (DSPN). Su objetivo es transformar ocho mediciones habituales de neuroconducción en dos resultados fáciles de interpretar.</p>
      <p><strong>Score #2 — Criterio diagnóstico compuesto:</strong> estima si existe un patrón de alteración de la conducción suficientemente distribuido entre varios nervios como para apoyar electrodiagnósticamente la presencia de polineuropatía.</p>
      <p><strong>Score #4 — Severidad por amplitudes:</strong> cuantifica el grado de reducción de las amplitudes de las respuestas nerviosas, como aproximación a la magnitud del compromiso axonal. Su clasificación de severidad es actualmente provisional y requiere validación clínica independiente.</p>
      <p>La herramienta evalúa cuatro nervios: tibial, fibular/peroneo, ulnar y sural, utilizando una medición de conducción y una amplitud por cada nervio, para un total de ocho variables.</p>
    </header>
    <Section title="¿De dónde proviene el sistema de puntuación?"><p>La estructura general se adaptó del concepto de scores compuestos de neuroconducción descrito por Davies y colaboradores. En ese trabajo, el criterio mínimo utilizado para neuropatía diabética fue la presencia de anormalidades de neuroconducción en más de un nervio periférico. Además, las velocidades de conducción y las latencias mostraron mayor utilidad para apoyar el diagnóstico, mientras que las amplitudes aportaron mayor información sobre severidad.</p><p>Esta aplicación no reproduce literalmente el score de Davies. Utiliza su marco conceptual, pero aplica límites normativos empíricos publicados por Buschbacher y por la Normative Data Task Force de la American Association of Neuromuscular &amp; Electrodiagnostic Medicine (AANEM).</p></Section>
    <Section title="¿Qué significa P3 o P97?"><p>Los estudios normativos analizan sujetos sin neuropatía y determinan qué valores se encuentran en los extremos de la población de referencia.</p><p>Para amplitudes y velocidades de conducción, el P3 se utiliza como límite inferior de normalidad: los valores por debajo de ese límite se consideran anormales.</p><p>Para la latencia pico del nervio sural se utiliza un P97, porque en este parámetro lo anormal es una latencia excesivamente prolongada. Los valores por encima del P97 se consideran anormales.</p><div className="rounded-lg border border-slate-200 bg-white p-4"><p className="font-semibold mb-2">En términos simples:</p><ul className="space-y-1"><li>• P3: aproximadamente solo el 3% de la población normativa presenta valores inferiores a este punto.</li><li>• P97: aproximadamente solo el 3% de la población normativa presenta valores superiores a este punto.</li></ul><p className="mt-2 text-slate-500">Esta es una explicación intuitiva de la posición percentilar y no representa la probabilidad de enfermedad de un paciente.</p></div><p>Estos límites son valores observados empíricamente en estudios normativos y no son calculados por la aplicación a partir de una distribución normal.</p></Section>
    <Section title="¿Qué es el percentil CDF descriptivo?"><p>Además del límite empírico que decide la puntuación, la aplicación calcula un percentil CDF descriptivo a partir de la media y desviación estándar de las bases normativas.</p><p>Ese percentil permite visualizar aproximadamente qué tan alejado está un resultado de la media normativa esperada, considerando edad y/o talla cuando corresponda al parámetro.</p><p className="rounded-lg border-l-4 border-blue-600 bg-blue-50 p-4 font-bold text-blue-950">El percentil CDF es únicamente descriptivo y nunca determina los puntos.</p><p>Esto es importante porque algunas variables neurofisiológicas, especialmente las amplitudes, no siguen perfectamente una distribución normal.</p></Section>
    <Section title="Score #2 — Criterio diagnóstico compuesto"><p>El Score #2 evalúa:</p><ol className="list-decimal pl-6 space-y-1"><li>Velocidad motora tibial</li><li>Velocidad motora fibular/peronea</li><li>Velocidad motora ulnar de antebrazo (below elbow)</li><li>Latencia pico sensitiva sural</li></ol><LimitCards groups={score2Limits.es}/><p className="text-xs text-slate-500"><strong>Fuente de los límites:</strong> valores motores derivados de Chen et al. y de la AANEM Normative Data Task Force; valores surales derivados de Buschbacher mediante neuroconducción sensitiva antidrómica a 14 cm.</p>
      <div className="space-y-2"><p><strong>0 puntos:</strong> la respuesta está presente y se encuentra dentro del límite empírico normal.</p><p><strong>1 punto:</strong> la respuesta está presente, pero se encuentra fuera del límite empírico normal.</p><p><strong>2 puntos:</strong> no se obtiene una respuesta reproducible, es decir, la respuesta es NR o no registrable.</p></div>
      <p className="bg-white border border-slate-200 rounded-lg p-4"><strong>Ejemplo:</strong> en una persona de 55 años y 165 cm, una velocidad tibial de 39 m/s se encuentra por encima del límite de 37 m/s y recibe 0 puntos. Una velocidad de 35 m/s es medible pero inferior al límite y recibe 1 punto. Si no se registra respuesta tibial, recibe 2 puntos.</p>
      <p>La suma de puntos se informa de 0 a 8, pero el criterio electrodiagnóstico compuesto no depende solamente de la suma de puntos.</p><p><strong>El criterio electrodiagnóstico compuesto se considera positivo únicamente cuando existen alteraciones en dos o más nervios anatómicamente diferentes.</strong></p>
      <div className="grid md:grid-cols-3 gap-3"><p className="rounded-lg bg-white border p-3"><strong>0 nervios anormales:</strong><br/>no se identifican alteraciones en los parámetros de conducción evaluados.</p><p className="rounded-lg bg-amber-50 border border-amber-200 p-3"><strong>1 nervio anormal:</strong><br/><b>ALTERACIÓN AISLADA.</b> No cumple el criterio compuesto para polineuropatía.</p><p className="rounded-lg bg-blue-50 border border-blue-200 p-3"><strong>≥2 nervios anormales:</strong><br/><b>CUMPLE EL CRITERIO DIAGNÓSTICO COMPUESTO.</b></p></div>
      <p>Cuando el sural y uno o más nervios motores están alterados, el patrón se describe como sensitivo-motor compatible con polineuropatía en el contexto clínico apropiado.</p><p>Cuando hay dos o más nervios motores alterados y el sural permanece normal, el criterio electrodiagnóstico compuesto también se considera positivo en esta herramienta, porque existen ≥2 nervios anatómicamente diferentes anormales. Este patrón requiere correlación con los hallazgos sensitivos y clínicos.</p><p className="font-semibold">Una reducción de velocidad por sí sola no debe interpretarse automáticamente como desmielinización.</p>
    </Section>
    <Section title="Score #4 — Severidad por amplitudes"><p>El Score #4 utiliza las amplitudes de las respuestas de los mismos cuatro nervios: CMAP tibial, CMAP fibular/peroneo, CMAP ulnar y SNAP sural.</p><p>La amplitud refleja principalmente cuántos axones funcionales contribuyen a la respuesta registrada. Una amplitud progresivamente reducida puede sugerir una pérdida funcional creciente de fibras nerviosas, aunque siempre debe interpretarse junto con el contexto clínico y técnico.</p><LimitCards groups={score4Limits.es}/><p className="text-xs text-slate-500"><strong>Fuente de los límites:</strong> límites de amplitud motora derivados de Chen et al. y de las referencias normativas de la AANEM; SNAP sural derivado de Buschbacher mediante neuroconducción sensitiva antidrómica a 14 cm.</p><div className="space-y-2"><p><strong>0 puntos:</strong> amplitud presente y dentro del límite P3.</p><p><strong>1 punto:</strong> amplitud presente pero por debajo del límite P3.</p><p><strong>2 puntos:</strong> respuesta ausente o no registrable.</p></div><ul className="rounded-lg bg-white border p-4 space-y-2"><li><strong>0 puntos — Sin evidencia de daño axonal según los parámetros evaluados</strong></li><li><strong>1–2 puntos — Leve</strong></li><li><strong>3–5 puntos — Moderada</strong></li><li><strong>6–8 puntos — Severa</strong></li></ul><p className="rounded-lg border-2 border-amber-300 bg-amber-50 p-4 font-semibold text-amber-950"><strong>IMPORTANTE:</strong> esta clasificación de severidad es una graduación operacional provisional de esta herramienta. No debe interpretarse como una escala de Davies validada ni como una clasificación universal. Debido a que la forma de asignar los puntos fue adaptada para utilizar P3/P97 empíricos y respuesta NR, estas bandas requieren validación clínica independiente.</p></Section>
    <Section title="¿En quién debe utilizarse?"><p>Esta herramienta está diseñada como apoyo para el análisis de estudios de neuroconducción en adultos entre 19 y 79 años con diabetes mellitus conocida o sospecha clínica de polineuropatía diabética distal simétrica.</p><p>Debe interpretarse junto con síntomas, examen neurológico, antecedentes metabólicos y el estudio electrodiagnóstico completo.</p><p>Una marcada asimetría, una distribución no dependiente de longitud o hallazgos clínicos atípicos deben motivar una evaluación electrodiagnóstica más amplia.</p><p><strong>No sustituye el juicio clínico del especialista.</strong></p></Section>
    <Section title="Referencias principales"><ScientificReferences /></Section>
  </article>;

  return <article className="p-5 md:p-7 border-t border-slate-100 bg-slate-50 text-sm md:text-[15px] text-slate-700 leading-relaxed space-y-8">
    <header className="space-y-3"><h2 className="text-xl md:text-2xl font-bold text-slate-900">How does this scoring system work?</h2><p>This application supports the electrodiagnostic analysis of distal symmetric sensorimotor diabetic polyneuropathy (DSPN). Its purpose is to transform eight routine nerve conduction measurements into two easy-to-interpret results.</p><p><strong>Score #2 — Composite diagnostic criterion:</strong> estimates whether conduction abnormalities are sufficiently distributed across several nerves to provide electrodiagnostic support for polyneuropathy.</p><p><strong>Score #4 — Amplitude severity:</strong> quantifies the reduction in nerve response amplitudes as an approximation of the magnitude of axonal involvement. Its severity classification is currently provisional and requires independent clinical validation.</p><p>The tool evaluates four nerves—tibial, fibular/peroneal, ulnar, and sural—using one conduction measurement and one amplitude for each nerve, for a total of eight variables.</p></header>
    <Section title="Where does the scoring system come from?"><p>The general structure was adapted from the concept of composite nerve conduction scores described by Davies and colleagues. In that study, the minimum criterion used for diabetic neuropathy was the presence of nerve conduction abnormalities in more than one peripheral nerve. Conduction velocities and latencies were more useful in supporting diagnosis, whereas amplitudes provided more information about severity.</p><p>This tool does not reproduce the original Davies score. It uses that conceptual framework but applies empirical reference limits published by Buschbacher and by the Normative Data Task Force of the American Association of Neuromuscular &amp; Electrodiagnostic Medicine (AANEM).</p></Section>
    <Section title="What do P3 and P97 mean?"><p>Normative studies examine people without neuropathy and determine which values lie at the extremes of the reference population.</p><p>For amplitudes and conduction velocities, P3 is used as the lower limit of normal: values below that limit are considered abnormal.</p><p>For sural peak latency, P97 is used as the upper limit because an excessively prolonged latency is abnormal. Values above P97 are considered abnormal.</p><div className="rounded-lg border border-slate-200 bg-white p-4"><p className="font-semibold mb-2">In simple terms:</p><ul className="space-y-1"><li>• P3: approximately only 3% of the normative population has values below this point.</li><li>• P97: approximately only 3% of the normative population has values above this point.</li></ul><p className="mt-2 text-slate-500">This is an intuitive explanation of percentile position, not a statement about an individual patient's probability of disease.</p></div><p>These limits are empirically observed values from normative studies and are not calculated by the application from a normal distribution.</p></Section>
    <Section title="What is the descriptive CDF percentile?"><p>In addition to the empirical reference limit that determines scoring, the application calculates a descriptive CDF percentile from the mean and standard deviation in the normative datasets.</p><p>This percentile provides an approximate view of how far a result lies from the expected normative mean, accounting for age and/or height when applicable to that parameter.</p><p className="rounded-lg border-l-4 border-blue-600 bg-blue-50 p-4 font-bold text-blue-950">The descriptive CDF percentile is descriptive only and never determines points.</p><p>This distinction matters because some neurophysiological variables, especially amplitudes, do not follow a perfectly normal distribution.</p></Section>
    <Section title="Score #2 — Composite diagnostic criterion"><p>Score #2 evaluates:</p><ol className="list-decimal pl-6 space-y-1"><li>Tibial motor velocity</li><li>Fibular/peroneal motor velocity</li><li>Forearm ulnar motor velocity (below elbow)</li><li>Sural sensory peak latency</li></ol><LimitCards groups={score2Limits.en}/><p className="text-xs text-slate-500"><strong>Source of the limits:</strong> motor values derived from Chen et al. and the AANEM Normative Data Task Force; sural values derived from Buschbacher using 14-cm antidromic sensory nerve conduction.</p><div className="space-y-2"><p><strong>0 points:</strong> the response is present and within the normal empirical reference limit.</p><p><strong>1 point:</strong> the response is present but outside the normal empirical reference limit.</p><p><strong>2 points:</strong> no reproducible response is obtained; that is, the response is NR or not recordable.</p></div><p className="bg-white border border-slate-200 rounded-lg p-4"><strong>Example:</strong> in a 55-year-old person who is 165 cm tall, a tibial velocity of 39 m/s is above the 37 m/s limit and receives 0 points. A measurable velocity of 35 m/s is below the limit and receives 1 point. If no tibial response is recorded, it receives 2 points.</p><p>The point total is reported from 0 to 8, but the composite electrodiagnostic criterion does not depend on the point total alone.</p><p><strong>The composite electrodiagnostic criterion is positive only when at least two anatomically distinct nerves are abnormal.</strong></p><div className="grid md:grid-cols-3 gap-3"><p className="rounded-lg bg-white border p-3"><strong>0 abnormal nerves:</strong><br/>no abnormalities are identified in the evaluated conduction parameters.</p><p className="rounded-lg bg-amber-50 border border-amber-200 p-3"><strong>1 abnormal nerve:</strong><br/><b>ISOLATED ABNORMALITY.</b> The composite criterion for polyneuropathy is not met.</p><p className="rounded-lg bg-blue-50 border border-blue-200 p-3"><strong>≥2 abnormal nerves:</strong><br/><b>MEETS THE COMPOSITE DIAGNOSTIC CRITERION.</b></p></div><p>When the sural nerve and one or more motor nerves are abnormal, the pattern is described as sensorimotor and compatible with polyneuropathy in the appropriate clinical context.</p><p>When two or more motor nerves are abnormal while the sural nerve remains normal, the composite electrodiagnostic criterion is also considered positive in this tool because ≥2 anatomically distinct nerves are abnormal. This pattern requires correlation with sensory and clinical findings.</p><p className="font-semibold">Reduced velocity alone should not automatically be interpreted as demyelination.</p></Section>
    <Section title="Score #4 — Amplitude severity"><p>Score #4 uses response amplitudes from the same four nerves: tibial CMAP, fibular/peroneal CMAP, ulnar CMAP, and sural SNAP.</p><p>Amplitude primarily reflects how many functioning axons contribute to the recorded response. A progressively reduced amplitude may suggest increasing functional loss of nerve fibers, although it must always be interpreted with the clinical and technical context.</p><LimitCards groups={score4Limits.en}/><p className="text-xs text-slate-500"><strong>Source of the limits:</strong> motor amplitude limits derived from Chen et al. and the AANEM normative references; sural SNAP derived from Buschbacher using 14-cm antidromic sensory nerve conduction.</p><div className="space-y-2"><p><strong>0 points:</strong> amplitude is present and within the P3 limit.</p><p><strong>1 point:</strong> amplitude is present but below the P3 limit.</p><p><strong>2 points:</strong> response is absent or not recordable.</p></div><ul className="rounded-lg bg-white border p-4 space-y-2"><li><strong>0 points — No evidence of axonal damage in the evaluated parameters</strong></li><li><strong>1–2 points — Mild</strong></li><li><strong>3–5 points — Moderate</strong></li><li><strong>6–8 points — Severe</strong></li></ul><p className="rounded-lg border-2 border-amber-300 bg-amber-50 p-4 font-semibold text-amber-950"><strong>IMPORTANT:</strong> this severity classification is a provisional operational grading used by this tool. It must not be interpreted as a validated Davies scale or as a universal classification. Because point assignment was adapted to use empirical P3/P97 limits and NR responses, these bands require independent clinical validation.</p></Section>
    <Section title="Who should this tool be used for?"><p>This tool is designed to support the analysis of nerve conduction studies in adults aged 19 to 79 years with known diabetes mellitus or clinical suspicion of distal symmetric diabetic polyneuropathy.</p><p>It must be interpreted together with symptoms, neurological examination, metabolic history, and the complete electrodiagnostic study.</p><p>Marked asymmetry, a non-length-dependent distribution, or atypical clinical findings should prompt a broader electrodiagnostic evaluation.</p><p><strong>It does not replace specialist clinical judgment.</strong></p></Section>
    <Section title="Main references"><ScientificReferences /></Section>
  </article>;
};
