import { NERVE_NAMES, NerveId, NerveType, type NerveReading, type PatientData, type ScoreDetail, type AnalysisResult, type AnalysisIssue } from '../types.ts';
import { TEXTS } from '../constants.ts';

export type MeasurementStatus = ScoreDetail['status'];
export type EmpiricalRule = Pick<ScoreDetail,'empiricalReferencePercentile'|'empiricalCutoff'|'cutoffDirection'|'empiricalRuleId'|'empiricalRuleDescription'>;

/**
 * The application implements an adapted composite electrodiagnostic score. Davies et al. provides the conceptual composite scoring framework; published Buschbacher/AANEM empirical P3/P97 reference limits are used as the primary abnormality thresholds. Normal-CDF percentiles are retained only as descriptive standardization. The adapted diagnostic and severity classifications require independent clinical validation.
 */
export const getEmpiricalRule=(nerveId:NerveId,parameter:ScoreDetail['parameter'],age:number,height:number,lang:'es'|'en'='es'):EmpiricalRule=>{
 let cutoff:number, id:string;
 if(nerveId===NerveId.SURAL&&parameter==='peakLatency'){cutoff=4.5;id='SURAL_LATENCY_P97';}
 else if(parameter==='velocity'){
  if(nerveId===NerveId.TIBIAL){cutoff=age<50?(height<160?44:height<170?42:37):(height<160?40:height<170?37:34);id=`TIBIAL_VELOCITY_P3_${age<50?'19_49':'50_79'}_${height<160?'LT160':height<170?'160_169':'GE170'}`;}
  else if(nerveId===NerveId.FIBULAR){cutoff=age<40?(height<170?43:37):(height<170?39:36);id=`FIBULAR_VELOCITY_P3_${age<40?'19_39':'40_79'}_${height<170?'LT170':'GE170'}`;}
  else if(nerveId===NerveId.ULNAR){cutoff=52;id='ULNAR_VELOCITY_P3';}
  else throw new Error(`Unsupported empirical rule combination: ${nerveId} + ${parameter}`);
 } else if(parameter==='amplitude') {
  if(nerveId===NerveId.TIBIAL){cutoff=age<30?5.8:age<60?5.3:1.1;id=`TIBIAL_AMPLITUDE_P3_${age<30?'19_29':age<60?'30_59':'60_79'}`;}
  else if(nerveId===NerveId.FIBULAR){cutoff=age<40?2.6:1.1;id=`FIBULAR_AMPLITUDE_P3_${age<40?'19_39':'40_79'}`;}
  else if(nerveId===NerveId.ULNAR){cutoff=7.9;id='ULNAR_AMPLITUDE_P3';}
  else if(nerveId===NerveId.SURAL){cutoff=4;id='SURAL_AMPLITUDE_P3';}
  else throw new Error(`Unsupported empirical rule combination: ${nerveId} + ${parameter}`);
 } else throw new Error(`Unsupported empirical rule combination: ${nerveId} + ${parameter}`);
 const upper=parameter==='peakLatency', percentile=upper?'P97':'P3', direction=upper?'UPPER_LIMIT':'LOWER_LIMIT';
 const description=lang==='es'?`${percentile} ${upper?'LSN':'LIN'} = ${cutoff} (${upper?'valores mayores son anormales':'valores menores son anormales'})`:`${percentile} ${upper?'ULN':'LLN'} = ${cutoff} (${upper?'higher values are abnormal':'lower values are abnormal'})`;
 return {empiricalReferencePercentile:percentile,empiricalCutoff:cutoff,cutoffDirection:direction,empiricalRuleId:id,empiricalRuleDescription:description};
};
export const calculateEmpiricalPoints=(value:number,rule:EmpiricalRule)=>rule.cutoffDirection==='LOWER_LIMIT'?(value<rule.empiricalCutoff?1:0):(value>rule.empiricalCutoff?1:0);

/** Numerical approximation of the standard normal CDF. */
export const normCDF=(x:number)=>{const t=1/(1+.2316419*Math.abs(x));const d=.3989423*Math.exp(-x*x/2);const p=d*t*(.3193815+t*(-.3565638+t*(1.7814779+t*(-1.821256+t*1.3302744))));return x>=0?1-p:p;};
export const getZScore=(value:number,mean:number,sd:number)=>(value-mean)/sd;
const lerp=(start:number,end:number,t:number)=>start*(1-t)+end*t;
const getTransitionFactor=(value:number,threshold:number,windowSize:number)=>{const start=threshold-windowSize/2,end=threshold+windowSize/2;if(value<=start)return 0;if(value>=end)return 1;return(value-start)/windowSize;};
export const getTibialAmpStats=(age:number)=>{const young={mean:15.3,sd:4.5},middle={mean:12.9,sd:4.5},old={mean:9.8,sd:4.2};const t1=getTransitionFactor(age,30,10),t2=getTransitionFactor(age,60,10);if(t1===0)return young;if(t1<1)return{mean:lerp(young.mean,middle.mean,t1),sd:lerp(young.sd,middle.sd,t1)};if(t2===0)return middle;return{mean:lerp(middle.mean,old.mean,t2),sd:lerp(middle.sd,old.sd,t2)};};
export const getFibularAmpStats=(age:number)=>{const t=getTransitionFactor(age,40,10);return{mean:lerp(6.8,5.1,t),sd:2.5};};
export const getTibialVelStats=(age:number,height:number)=>{const ih=(h:number,a:number,b:number,c:number)=>h<=155?a:h>=175?c:h<165?lerp(a,b,(h-155)/10):lerp(b,c,(h-165)/10);const t=getTransitionFactor(age,50,10);return{mean:lerp(ih(height,51,49,47),ih(height,49,45,44),t),sd:lerp(ih(height,4,6,5),5,t)};};
export const getFibularVelStats=(age:number,height:number)=>{const th=getTransitionFactor(height,170,10),ta=getTransitionFactor(age,40,10);return{mean:lerp(lerp(49,46,th),lerp(47,44,th),ta),sd:lerp(4,lerp(5,4,th),ta)};};

const parseMeasurement=(raw:string|number|undefined,amplitude:boolean):{status:MeasurementStatus;value?:number;display:string|number}=>{if(raw===undefined||(typeof raw==='string'&&raw.trim()===''))return{status:'MISSING',display:''};if(typeof raw==='string'&&['NR','N'].includes(raw.trim().toUpperCase()))return{status:'NR',display:'NR'};const normalized=typeof raw==='string'?raw.trim().replace(',','.'):raw;if((typeof normalized==='string'&&!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(normalized))||!Number.isFinite(Number(normalized)))return{status:'INVALID',display:String(raw)};const value=Number(normalized);if(amplitude&&value===0)return{status:'NR',value:0,display:'NR (0)'};if(value<=0)return{status:'INVALID',value,display:value};return{status:'VALID',value,display:value};};
const makeDetail=(nerveId:NerveId,nerve:string,parameter:ScoreDetail['parameter'],unit:ScoreDetail['unit'],raw:string|number|undefined,stats:{mean:number;sd:number},age:number,height:number,lang:'es'|'en'):ScoreDetail=>{const parsed=parseMeasurement(raw,parameter==='amplitude'),rule=getEmpiricalRule(nerveId,parameter,age,height,lang);const base={nerveId,nerve,parameter,unit,value:parsed.display,status:parsed.status,referenceMean:stats.mean,referenceSD:stats.sd,points:null,...rule};if(parsed.status==='NR')return{...base,points:2};if(parsed.status!=='VALID'||parsed.value===undefined)return base;const zScore=getZScore(parsed.value,stats.mean,stats.sd),descriptiveCDFPercentile=normCDF(zScore);return{...base,value:parsed.value,zScore,descriptiveCDFPercentile,points:calculateEmpiricalPoints(parsed.value,rule)};};
const EXPECTED:Record<NerveId,NerveType>={[NerveId.TIBIAL]:NerveType.MOTOR,[NerveId.FIBULAR]:NerveType.MOTOR,[NerveId.ULNAR]:NerveType.MOTOR,[NerveId.SURAL]:NerveType.SENSORY};
const validateReadings=(readings:NerveReading[])=>{const known=new Set(Object.values(NerveId));for(const r of readings){if(!known.has(r.nerveId as NerveId))throw new Error(`Unknown nerve identifier: ${String(r.nerveId)}`);if(r.nerveName!==NERVE_NAMES[r.nerveId])throw new Error(`Nerve name does not match identifier ${r.nerveId}: expected ${NERVE_NAMES[r.nerveId]}`);}for(const id of Object.values(NerveId)){const matches=readings.filter(r=>r.nerveId===id);if(matches.length===0)throw new Error(`Required nerve is missing: ${id}`);if(matches.length>1)throw new Error(`Duplicate nerve measurement: ${id}`);if(matches[0].type!==EXPECTED[id])throw new Error(`Incorrect nerve type for ${id}: expected ${EXPECTED[id]}`);}if(readings.length!==4)throw new Error('Exactly four required nerve measurements are allowed.');};
// Provisional mapping retained after redefining individual 0/1/2 rules; independent clinical validation is required.
export const getScore4Severity=(total:number,lang:'es'|'en'='es')=>total>=6?TEXTS[lang].severe:total>=3?TEXTS[lang].moderate:total>=1?TEXTS[lang].mild:TEXTS[lang].noAxonalDamage;
export const classifyScore2=(details:ScoreDetail[],lang:'es'|'en'='es')=>{const abnormal=details.filter(d=>(d.points??0)>0),names=abnormal.map(d=>d.nerve.replace(/ \(.+\)/,''));if(!abnormal.length)return TEXTS[lang].s2NormalBody;if(abnormal.length===1)return (lang==='es'?`Se identifica alteración aislada de la neuroconducción en ${names[0]}. No cumple el criterio electrodiagnóstico compuesto de anormalidad en ≥2 nervios diferentes para polineuropatía diabética.`:`An isolated nerve-conduction abnormality is identified in the ${names[0]} nerve. The composite electrodiagnostic criterion of abnormality in ≥2 different nerves for diabetic polyneuropathy is not met.`);const sural=abnormal.some(d=>d.nerveId===NerveId.SURAL),motor=abnormal.some(d=>d.nerveId!==NerveId.SURAL);return sural&&motor?TEXTS[lang].s2SensorimotorBody:TEXTS[lang].s2AbnormalGeneric;};
export const runFullAnalysis=(readings:NerveReading[],patient:PatientData,lang:'es'|'en'='es'):AnalysisResult=>{
 if(!Number.isFinite(patient.age)||patient.age<19||patient.age>79)throw new RangeError(TEXTS[lang].ageValidation);if(!Number.isFinite(patient.height)||patient.height<=0)throw new RangeError(TEXTS[lang].heightValidation);validateReadings(readings);const score2Details:ScoreDetail[]=[],score4Details:ScoreDetail[]=[];
 for(const r of readings){let stats:{amp:{mean:number;sd:number};vel?:{mean:number;sd:number};lat?:{mean:number;sd:number}};switch(r.nerveId){case NerveId.TIBIAL:stats={amp:getTibialAmpStats(patient.age),vel:getTibialVelStats(patient.age,patient.height)};break;case NerveId.FIBULAR:stats={amp:getFibularAmpStats(patient.age),vel:getFibularVelStats(patient.age,patient.height)};break;case NerveId.ULNAR:stats={amp:{mean:11.6,sd:2.1},vel:{mean:61,sd:5}};break;case NerveId.SURAL:stats={amp:{mean:17,sd:10},lat:{mean:3.8,sd:.3}};break;default:throw new Error(`Unknown nerve identifier: ${String(r.nerveId)}`);}if(r.nerveId===NerveId.SURAL)score2Details.push(makeDetail(r.nerveId,r.nerveName,'peakLatency','ms',r.peakLatency,stats.lat!,patient.age,patient.height,lang));else score2Details.push(makeDetail(r.nerveId,r.nerveName,'velocity','m/s',r.velocity,stats.vel!,patient.age,patient.height,lang));score4Details.push(makeDetail(r.nerveId,r.nerveName,'amplitude',r.nerveId===NerveId.SURAL?'µV':'mV',r.amplitude,stats.amp,patient.age,patient.height,lang));}
 const issues:AnalysisIssue[]=[...score2Details.map(d=>({...d,score:'SCORE_2' as const})),...score4Details.map(d=>({...d,score:'SCORE_4' as const}))].filter(d=>d.status==='MISSING'||d.status==='INVALID').map(d=>({score:d.score,nerveId:d.nerveId,nerve:d.nerve,parameter:d.parameter,status:d.status as 'MISSING'|'INVALID'}));
 for(const nerveId of Object.values(NerveId)){const conduction=score2Details.find(d=>d.nerveId===nerveId)!,amplitude=score4Details.find(d=>d.nerveId===nerveId)!;if((amplitude.status==='NR'&&conduction.status==='VALID')||(conduction.status==='NR'&&amplitude.status==='VALID'))issues.push({score:'SCORE_2',nerveId,nerve:conduction.nerve,parameter:conduction.parameter,status:'INCONSISTENT',message:lang==='es'?'Respuesta ausente/NR incompatible con un valor numérico positivo en el par amplitud–conducción.':'Absent/NR response is inconsistent with a positive numeric value in the paired amplitude–conduction fields.'});}
 if(issues.length)return{analysisStatus:'INCOMPLETE_ANALYSIS',issues,score2:{total:null,isAbnormal:null,status:null,abnormalNerveCount:null,meetsCompositeCriterion:null,details:score2Details,interpretationBody:null},score4:{total:null,isAbnormal:null,details:score4Details,severityLabel:null},severityClass:null,diagnosisClass:null};
 const s2Total=score2Details.reduce((n,d)=>n+d.points!,0),s4Total=score4Details.reduce((n,d)=>n+d.points!,0),abnormalNerveCount=new Set(score2Details.filter(d=>d.points!>0).map(d=>d.nerveId)).size,meetsCompositeCriterion=abnormalNerveCount>=2,status=abnormalNerveCount===0?'NO_ABNORMALITY':abnormalNerveCount===1?'ISOLATED_ABNORMALITY':'COMPOSITE_POSITIVE',interpretationBody=classifyScore2(score2Details,lang),diagnosisClass=status==='NO_ABNORMALITY'?TEXTS[lang].normal:status==='ISOLATED_ABNORMALITY'?(lang==='es'?'ALTERACIÓN AISLADA':'ISOLATED ABNORMALITY'):TEXTS[lang].abnormal,severityLabel=getScore4Severity(s4Total,lang);return{analysisStatus:'VALID_ANALYSIS',issues:[],score2:{total:s2Total,isAbnormal:meetsCompositeCriterion,status,abnormalNerveCount,meetsCompositeCriterion,details:score2Details,interpretationBody},score4:{total:s4Total,isAbnormal:s4Total>=1,details:score4Details,severityLabel},severityClass:`${diagnosisClass} / ${severityLabel}`,diagnosisClass};
};
